from archlinux
copy pacman.conf /etc/pacman.conf
copy mirrorlist /etc/pacman.d/mirrorlist
copy entrypoint.sh /entrypoint.sh

arg http_proxy=
arg https_proxy=
arg socks_proxy=
arg GROUPID=
arg USERNAME=
arg USERID=

run pacman -Sy
run pacman -Su --noconfirm
run pacman -S --noconfirm archlinux-keyring yay git neovim fzf fd lazygit ripgrep universal-ctags gcc nodejs xsel npm python3 python-pip fish sudo docker
run git clone https://ghproxy.com/https://github.com/skyfireitdiy/dotfile /dotfile
run groupadd -g $GROUPID $USERNAME
run useradd -g $USERNAME -u $USERID -d /home/$USERNAME -m -s /usr/bin/fish $USERNAME
run echo 'skyfire ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

entrypoint /entrypoint.sh
workdir /home/$USERNAME

